wallpaper {
  monitor = DP-1
  path = ~/.config/hypr/frieren.jpeg
  fit_mode = cover
}
wallpaper {
  monitor = HDMI-A-1
  path = ~/.config/hypr/frieren.jpeg
  fit_mode = cover
}
wallpaper {
  monitor = DVI-D-1
  path = ~/.config/hypr/frieren.jpeg
  fit_mode = cover
}
