wallpaper {
  monitor = DP-1
  path = ~/.config/hypr/hjeusarts-abstract.jpg
  fit_mode = cover
}
wallpaper {
  monitor = HDMI-A-1
  path = ~/.config/hypr/hjeusarts-abstract.jpg
  fit_mode = cover
}
wallpaper {
  monitor = DVI-D-1
  path = ~/.config/hypr/hjeusarts-abstract.jpg
  fit_mode = cover
}

splash = false
